[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_WEBPACK_USEPOLLING = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000 